// <auto-generated />
namespace POS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class penjualandtlpenjualanHdr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(penjualandtlpenjualanHdr));
        
        string IMigrationMetadata.Id
        {
            get { return "201407190636140_penjualandtl - penjualanHdr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
